### ISSUE TITLE
setlocale.c should include <string.h>

### ISSUE THREAD

**Issue by czietz** [mfro0/libcmini#31]
setlocale.c uses strncpy and therefore should include <string.h> to avoid calling a function without a prototype:
https://github.com/mfro0/libcmini/blob/ca8f585156f3f3f3a00c82f3f1e236eec968b173/sources/setlocale.c#L11

**Comment by mfro0** [comment]
Fixed with 6de923c061911ca6977ca09eec0c65ae50a42dbd

Thank you!
