### ISSUE TITLE
strcmp wrong

### ISSUE THREAD

**Issue by czietz** [mfro0/libcmini#32]
Consider the following example:

```c
#include <stdio.h>
#include <string.h>

void testcmp(const char* s1, const char* s2)
{
    int cmp = strcmp(s1, s2);
    if (cmp>0) {
        printf("'%s' > '%s'\n", s1, s2);
    } else if (cmp<0) {
        printf("'%s' < '%s'\n", s1, s2);
    } else {
        printf("'%s' = '%s'\n", s1, s2);
    }
}

int main(void)
{
    testcmp("abc", "def");
    testcmp("def", "def");
    testcmp("def", "abc");
    
    testcmp("abc", "");
    testcmp("abc", "ab");
    testcmp("", "abc");
    testcmp("ab", "abc");

    return 0;
}
```

Expected output is...
```
'abc' < 'def'
'def' = 'def'
'def' > 'abc'
'abc' > ''
'abc' > 'ab'
'' < 'abc'
'ab' < 'abc'
```

Output when using libcmini is...
```
'abc' < 'def'
'def' = 'def'
'def' > 'abc'
'abc' = ''
'abc' = 'ab'
'' = 'abc'
'ab' = 'abc'
```

This line...
https://github.com/mfro0/libcmini/blob/67e3c67164e19bff991991c2ba22495d14d1a9cc/sources/strcmp.c#L14
... causes the comparison to end at a NUL terminator, without taking into account that one string maybe longer. In particular, when either of the strings is empty, the return value will even be undefined, because `cmp` is not initialized.

**Comment by czietz** [comment]
PS: The following should work -- not thoroughly tested:
```c
for ( ; *s1 && *s1 == *s2; s1++, s2++)
    ;
return *s1 - *s2;
```

**Comment by sqward** [comment]
This is how my local change looks:

int strcmp(const char *s1, const char *s2)
{
    while (*s1 && *s1 == *s2) s1++, s2++;
	return (*s1 - *s2);

}

**Comment by mfro0** [comment]
Fixed. Thank you very much, gentlemen.
