### ISSUE TITLE
strchr failes on non-ascii characters

### ISSUE THREAD

**Issue by th-otto** [mfro0/libcmini#51]
Commit https://github.com/mfro0/libcmini/commit/b3e7dbd0375889eff82c84ce601c4468dff0d0d5 did not only add memchr, but also includes a broken change to strchr. strchr(str, 0xb0) now fails because *p is sign-extended.

**Comment by rosenrost** [comment]
I did a few tests and one thing is that you cannot test library functions when using gcc optimizing. gcc seems to replace several standard functions by its own code. So, for testing purposes no -O switches should be used for compiling.

**Comment by th-otto** [comment]
Sorry but that's nonsense. Gcc surely does not replace the *implementation* of strchr. Just look at the produced code. Also it would be totally useless to test a library without optimization, find that it works, and then the optimized version is still broken because you used some dubious constructs like aliased pointers.

**Comment by rosenrost** [comment]
You can call it nonsense, but I saw it a few minutes ago.
```
unsigned char t[] = { 'X', 0xb0, 0 };
const char* text = (char*)t;
printf("%p %p\n", text, strchr(text, 0xb0));
```
returned:
"<address of text> 0x0" when compiled with no optimization switch,
"<address of text> <address of text plus 1> when compiled with -Os
"<address of text> <address of text plus 1> when compiled with -O2

However, you are certainly right with "-fno-builtin".

**Comment by rosenrost** [comment]
And, speaking of "-fno-builtin":

> GCC normally generates special code to handle certain built-in functions more efficiently; for instance, calls to "alloca" may become single instructions that adjust the stack directly, and calls to "memcpy" may become inline copy loops.

> The ISO C90 functions abort, abs, acos, asin, atan2, atan, calloc, ceil, cosh, cos, exit, exp, fabs, floor, fmod, fprintf, fputs, frexp, fscanf, isalnum, isalpha, iscntrl, isdigit, isgraph, islower, isprint, ispunct, isspace, isupper, isxdigit, tolower, toupper, labs, ldexp, log10, log, malloc, memchr, memcmp, memcpy, memset, modf, pow, printf, putchar, puts, scanf, sinh, sin, snprintf, sprintf, sqrt, sscanf, strcat, **strchr**, strcmp, strcpy, strcspn, strlen, strncat, strncmp, strncpy, strpbrk, strrchr, strspn, strstr, tanh, tan, vfprintf, vprintf and vsprintf are all recognized as built-in functions unless -fno-builtin is specified (or -fno-builtin-function is specified for an individual function).

https://www.cleancss.com/explain-command/gcc/4649
https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html

**Comment by th-otto** [comment]
> 0x0" when compiled with no optimization switch,

Yes, because then it uses the broken library implementation.

**Comment by rosenrost** [comment]
That's what I said. ;)

**Comment by th-otto** [comment]
btw. -fno-builtin would also be a good check whether the compiler generates any calls to functions that are not implemented in libcmini, and thus could cause a linker error. The list above is a start, but that list is constantly growing with almost every GCC release.
