### ISSUE TITLE
fcloseall broken

### ISSUE THREAD

**Issue by th-otto** [mfro0/libcmini#52]
There are  (at least) 5 issues with fcloseall():

- it is a non-standard function, so should not be there
- it has an extern declaration of a public variable
- it has no prototype
- it is not declared in any header file
- if accesses f->__next in the loop on a structure that just has been freed by fclose()

**Comment by rosenrost** [comment]
>     * it is a non-standard function, so should not be there
fcloseall() is a GNU extension, but it is very handy. So why not offer it? Mintlib offers it, too.

>     * it has an extern declaration of a public variable
Fixed.

>     * it is not declared in any header file
>     * it has no prototype
No, look at stdio.h!

>     * if accesses f->__next in the loop on a structure that just has been freed by fclose()
Fixed. However, this is an issue to mintlib as well, at least up to March 4, 2017. ;)

**Comment by th-otto** [comment]
>Mintlib offers it, too.

Yes, i saw that. That's probably because mintlib is based on an old version of glibc. But i think it should not be in libcmini, otherwise you are just starting to re-implement mintlib.

>No, look at stdio.h!

Yes, but only by a later commit. And the definition still lacks a prototype.

>However, this is an issue to mintlib as well, at least up to March 4, 2017. ;)

Not really, because FILEs are not malloced there. I've fixed it there, nevertheless.

**Comment by rosenrost** [comment]
> > Mintlib offers it, too.
> 
> Yes, i saw that. That's probably because mintlib is based on an old version of glibc. But i think it should not be in libcmini, otherwise you are just starting to re-implement mintlib.
But the purpose of libcmini is to avoid all that overhead needed for the MiNT environment. And if one doesn't use that function, it won't be linked and so won't waste memory.

> > No, look at stdio.h!
> 
> Yes, but only by a later commit. And the definition still lacks a prototype.

What's your definition of a prototype?
Excerpt from stdio.h
`extern int fcloseall();
`
What's wrong with that?

> > However, this is an issue to mintlib as well, at least up to March 4, 2017. ;)
> Not really, because FILEs are not malloced there. I've fixed it there, nevertheless.
I didn't know that. Forget my annotation. ;)

**Comment by rosenrost** [comment]
> > Mintlib offers it, too.
> 
> Yes, i saw that. That's probably because mintlib is based on an old version of glibc. But i think it should not be in libcmini, otherwise you are just starting to re-implement mintlib.
But the purpose of libcmini is to avoid all that overhead needed for the MiNT environment. And if one doesn't use that function, it won't be linked and so won't waste memory.

> > No, look at stdio.h!
> Yes, but only by a later commit. And the definition still lacks a prototype.
What's your definition of a prototype?
Excerpt from stdio.h::
`extern int fcloseall();
`What's wrong with that?

> > However, this is an issue to mintlib as well, at least up to March 4, 2017. ;)
> Not really, because FILEs are not malloced there. I've fixed it there, nevertheless.
I didn't know that. Forget my annotation. ;)

**Comment by th-otto** [comment]
>What's your definition of a prototype?

Sigh. Your declaration just declares the return type, not that the function takes no parameters.

**Comment by th-otto** [comment]
> if one doesn't use that function, it won't be linked and so won't waste memory.

But FILEs in libcmini are not buffered, and the file handles itself will be closed by the OS anyway, so that function is rather useless here.

**Comment by th-otto** [comment]
> if one doesn't use that function, it won't be linked and so won't waste memory.

And that isn't true either, because you are calling it now in exit(), which will always be referenced from the startup code.

**Comment by rosenrost** [comment]
What's the problem with that as exit() would perform the same loop?

**Comment by mfro0** [comment]
I have removed the `fcloseall()` from `exit()` for now
