### ISSUE TITLE
localtime/mktime broken

### ISSUE THREAD

**Issue by th-otto** [mfro0/libcmini#54]
I don't see any reference to a timezone offset there. Those functions are totally crap, and will only return bogus values.

**Comment by rosenrost** [comment]
Yes, these functions lack timezone support as well as dst. At the moment, the easiest way to implement at least timezones would be the Pure C solution. Pure C uses a global signed long variable "timezone" which can be set to an offset in seconds. Additionally a TZ environment variable can be evaluated with some limitations to e.g. UTC offset notation.

The lack of dst recognition still remains as this would at least be country-dependend to cover the time_t range from Dec 1901 until Jan 2038 and thus would need memory as well as maintenance.

**Comment by th-otto** [comment]
Yes, of course supporting that for arbitrary dates is not possible without a timezone database. But at least an offset should be definable somewhere, and getenv("TZ") supported, otherwise gmtime will just produce times for GMT+0. If the program is running under MiNT, there is also some way to query the offset from there IIRC.

**Comment by rosenrost** [comment]
I am working on that.

**Comment by rosenrost** [comment]
It's in the pipeline. Might take a few days.

**Comment by rosenrost** [comment]
One question after I played around with Linux and Cygwin bash and the TZ environment variable:

Suppose it's 20:15 now. With different TZ values I get the following responses:

date -> Mo, 22. Jul 2019 20:15:25
TZ="UTC" date -> Mo, 22. Jul 2019 18:15:25

That's what I expected. But!!

TZ="UTC+02:00" date -> Mo, 22. Jul 2019 16:15:25
TZ="UTC-02:00" date -> Mo, 22. Jul 2019 20:15:25

I would have expected the opposite as CET with DST is UTC+2:

TZ="CET" date -> Mo, 22. Jul 2019 20:15:25

**Comment by mfro0** [comment]
please see my comments in pull request #65

**Comment by mfro0** [comment]
Let's consider that fixed by #65
