### ISSUE TITLE
snprintf/vnsprintf returns wrong result if buffer was not large enough

### ISSUE THREAD

**Issue by th-otto** [mfro0/libcmini#58]
The current implementation always returns the number that have actually been written. When the buffer was not large enough, it should return the number that *would* have been written.

**Comment by rosenrost** [comment]
I cannot confirm that. The following code:

```
char buf[10];
int r = snprintf(buf, 10, "%-40s", "Blah");
printf("%d \"%s\"\r\n", r,buf);
```

returns
`40 "Blah      "`
(with five blanks after "Blah" as expected.

**Comment by th-otto** [comment]
Hm. sry, must have accidently been using an older library when compiling the test.
