### ISSUE TITLE
gmtime (and localtime) broken in -mshort builds

### ISSUE THREAD

**Issue by czietz** [mfro0/libcmini#79]
`gmtime()` and therefore `localtime()` do not work correctly in the _-mshort_ builds of libcmini, i.e., builds with 16-bit integers. Consider the following test program:

```
#include <stdio.h>
#include <time.h>

int main(void)
{
    struct tm *tm;
    time_t today = 1571676862L;
    tm = gmtime(&today);
    printf("%d.%02d.%04d %02d:%02d\r\n", tm->tm_mday, tm->tm_mon+1, 
                                         tm->tm_year+1900, tm->tm_hour, tm->tm_min);
    return 0;
}
```

... that will output `21.10.2019 -1:-17`. This is caused by doing all time calculation in integers instead of in long integers in https://github.com/mfro0/libcmini/blob/master/sources/gmtime.c.

Note that also some constants (such as 86399) need to be fixed (86399L) in this file.

libcmini should be thoroughly checked for similar bugs in other files.

**Comment by czietz** [comment]
At least `tzset()` suffers from a similar issue, if the time zone offset (specified via the _TZ_ environment variable) becomes to big:
https://github.com/mfro0/libcmini/blob/5ef8c12c47c5de3169a24ab1594bf143f2fe28d3/sources/tzset.c#L146

**Comment by rosenrost** [comment]
It's on my agenda.
